apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-two12-co-tls
spec:
  secretName: k8s-two12-co
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.two12.co
  dnsNames:
    - k8s.two12.co
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.two12.co