apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-two12-co-tls
spec:
  secretName: k8s-two12-co
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: k8s.two12.co
  dnsNames:
    - k8s.two12.co